// import { useState } from "react";
import { nanoid } from "nanoid";
import "./App.scss";
import Word from "./components/Word";

function App() {
  function scatter(margin = 100) {
    var height = window.innerHeight - margin * 2;
    var width = window.innerWidth - margin * 2;
    var top = Math.random() * width + margin / 1.5;
    var left = Math.random() * height + margin / 1.5;
    return [top, left];
  }
  const words = [
    { word: "&", frequency: "2" },
    { word: "a", frequency: "6" },
    { word: "about", frequency: "1" },
    { word: "above", frequency: "1" },
    { word: "ache", frequency: "1" },
    { word: "ad", frequency: "1" },
    { word: "after", frequency: "1" },
    { word: "all", frequency: "1" },
    { word: "am", frequency: "2" },
    { word: "an", frequency: "2" },
    { word: "and", frequency: "4" },
    { word: "apparatus", frequency: "1" },
    { word: "are", frequency: "2" },
    { word: "arm", frequency: "1" },
    { word: "as", frequency: "4" },
    { word: "ask", frequency: "1" },
    { word: "at", frequency: "3" },
    { word: "away", frequency: "1" },
    { word: "bare", frequency: "1" },
    { word: "be", frequency: "1" },
    { word: "beat", frequency: "1" },
    { word: "beauty", frequency: "1" },
    { word: "bed", frequency: "1" },
    { word: "beneath", frequency: "1" },
    { word: "bitter", frequency: "1" },
    { word: "black", frequency: "1" },
    { word: "blood", frequency: "1" },
    { word: "blow", frequency: "1" },
    { word: "blue", frequency: "1" },
    { word: "boil", frequency: "1" },
    { word: "boy", frequency: "1" },
    { word: "breast", frequency: "1" },
    { word: "but", frequency: "4" },
    { word: "butt", frequency: "1" },
    { word: "by", frequency: "2" },
    { word: "can", frequency: "1" },
    { word: "chant", frequency: "1" },
    { word: "chocolate", frequency: "1" },
    { word: "cool", frequency: "1" },
    { word: "could", frequency: "1" },
    { word: "crush", frequency: "1" },
    { word: "cry d", frequency: "1" },
    { word: "day", frequency: "1" },
    { word: "death", frequency: "1" },
    { word: "delirious", frequency: "1" },
    { word: "diamond", frequency: "1" },
    { word: "did", frequency: "1" },
    { word: "do", frequency: "2" },
    { word: "dream", frequency: "1" },
    { word: "dress", frequency: "1" },
    { word: "drive", frequency: "1" },
    { word: "drool", frequency: "1" },
    { word: "drunk", frequency: "1" },
    { word: "eat", frequency: "1" },
    { word: "ed", frequency: "4" },
    { word: "egg", frequency: "1" },
    { word: "elaborate", frequency: "1" },
    { word: "enormous", frequency: "1" },
    { word: "er", frequency: "1" },
    { word: "es", frequency: "1" },
    { word: "est", frequency: "1" },
    { word: "fast", frequency: "1" },
    { word: "feet", frequency: "1" },
    { word: "fiddle", frequency: "1" },
    { word: "finger", frequency: "1" },
    { word: "fluff", frequency: "1" },
    { word: "for", frequency: "1" },
    { word: "forest", frequency: "1" },
    { word: "frantic", frequency: "1" },
    { word: "friend", frequency: "1" },
    { word: "from", frequency: "2" },
    { word: "garden", frequency: "1" },
    { word: "gir", frequency: "1" },
    { word: "l", frequency: "1" },
    { word: "go", frequency: "1" },
    { word: "goddess", frequency: "1" },
    { word: "gorgeous", frequency: "1" },
    { word: "gown", frequency: "1" },
    { word: "hair", frequency: "1" },
    { word: "has", frequency: "1" },
    { word: "have", frequency: "2" },
    { word: "he", frequency: "2" },
    { word: "head", frequency: "1" },
    { word: "heave", frequency: "1" },
    { word: "her", frequency: "2" },
    { word: "here", frequency: "1" },
    { word: "him", frequency: "1" },
    { word: "his", frequency: "2" },
    { word: "honey", frequency: "1" },
    { word: "hot", frequency: "1" },
    { word: "how", frequency: "1" },
    { word: "I", frequency: "4" },
    { word: "if", frequency: "1" },
    { word: "in", frequency: "3" },
    { word: "ing", frequency: "6" },
    { word: "is", frequency: "5" },
    { word: "it", frequency: "3" },
    { word: "juice", frequency: "1" },
    { word: "lake", frequency: "1" },
    { word: "language", frequency: "1" },
    { word: "languid", frequency: "1" },
    { word: "lather", frequency: "1" },
    { word: "lazy", frequency: "1" },
    { word: "less", frequency: "1" },
    { word: "let", frequency: "1" },
    { word: "lick", frequency: "1" },
    { word: "lie", frequency: "1" },
    { word: "life", frequency: "1" },
    { word: "light", frequency: "1" },
    { word: "like", frequency: "3" },
    { word: "live", frequency: "1" },
    { word: "love", frequency: "1" },
    { word: "luscious", frequency: "1" },
    { word: "lust", frequency: "1" },
    { word: "ly", frequency: "4" },
    { word: "mad", frequency: "1" },
    { word: "man", frequency: "1" },
    { word: "me", frequency: "3" },
    { word: "mean", frequency: "1" },
    { word: "meat", frequency: "1" },
    { word: "men", frequency: "1" },
    { word: "milk", frequency: "1" },
    { word: "mist", frequency: "1" },
    { word: "moan", frequency: "1" },
    { word: "moon", frequency: "1" },
    { word: "mother", frequency: "1" },
    { word: "music", frequency: "1" },
    { word: "must", frequency: "1" },
    { word: "my", frequency: "3" },
    { word: "need", frequency: "1" },
    { word: "never", frequency: "1" },
    { word: "no", frequency: "2" },
    { word: "not", frequency: "2" },
    { word: "of", frequency: "4" },
    { word: "on", frequency: "2" },
    { word: "one", frequency: "1" },
    { word: "or", frequency: "1" },
    { word: "our", frequency: "1" },
    { word: "over", frequency: "1" },
    { word: "pant", frequency: "1" },
    { word: "peach", frequency: "1" },
    { word: "petal", frequency: "1" },
    { word: "picture", frequency: "1" },
    { word: "pink", frequency: "1" },
    { word: "play", frequency: "1" },
    { word: "please", frequency: "1" },
    { word: "pole", frequency: "1" },
    { word: "pound", frequency: "1" },
    { word: "puppy", frequency: "1" },
    { word: "purple", frequency: "1" },
    { word: "put", frequency: "1" },
    { word: "r", frequency: "2" },
    { word: "rain", frequency: "1" },
    { word: "raw", frequency: "1" },
    { word: "recall", frequency: "1" },
    { word: "red", frequency: "1" },
    { word: "repulsive", frequency: "1" },
    { word: "rip", frequency: "1" },
    { word: "rock", frequency: "1" },
    { word: "rose", frequency: "1" },
    { word: "run", frequency: "1" },
    { word: "rust", frequency: "1" },
    { word: "s", frequency: "11" },
    { word: "sad", frequency: "1" },
    { word: "said", frequency: "1" },
    { word: "sausage", frequency: "1" },
    { word: "say", frequency: "1" },
    { word: "scream", frequency: "1" },
    { word: "sea", frequency: "1" },
    { word: "see", frequency: "1" },
    { word: "shadow", frequency: "1" },
    { word: "she", frequency: "2" },
    { word: "shine", frequency: "1" },
    { word: "ship", frequency: "1" },
    { word: "shot", frequency: "1" },
    { word: "show", frequency: "1" },
    { word: "sing", frequency: "1" },
    { word: "sit", frequency: "1" },
    { word: "skin", frequency: "1" },
    { word: "sky", frequency: "1" },
    { word: "sleep", frequency: "1" },
    { word: "smear", frequency: "1" },
    { word: "smell", frequency: "1" },
    { word: "smooth", frequency: "1" },
    { word: "so", frequency: "1" },
    { word: "soar", frequency: "1" },
    { word: "some", frequency: "1" },
    { word: "sordid", frequency: "1" },
    { word: "spray", frequency: "1" },
    { word: "spring", frequency: "1" },
    { word: "still", frequency: "1" },
    { word: "stop", frequency: "1" },
    { word: "storm", frequency: "1" },
    { word: "suit", frequency: "1" },
    { word: "summer", frequency: "1" },
    { word: "sun", frequency: "1" },
    { word: "sweat", frequency: "1" },
    { word: "swee", frequency: "1" },
    { word: "t", frequency: "1" },
    { word: "swim", frequency: "1" },
    { word: "symphony", frequency: "1" },
    { word: "the", frequency: "5" },
    { word: "their", frequency: "1" },
    { word: "there", frequency: "1" },
    { word: "these", frequency: "1" },
    { word: "they", frequency: "1" },
    { word: "those", frequency: "1" },
    { word: "though", frequency: "1" },
    { word: "thousand", frequency: "1" },
    { word: "through", frequency: "1" },
    { word: "time", frequency: "1" },
    { word: "tiny", frequency: "1" },
    { word: "to", frequency: "3" },
    { word: "together", frequency: "1" },
    { word: "tongue", frequency: "1" },
    { word: "trudge", frequency: "1" },
    { word: "TV", frequency: "1" },
    { word: "ugly", frequency: "1" },
    { word: "up", frequency: "1" },
    { word: "urge", frequency: "1" },
    { word: "us", frequency: "1" },
    { word: "use", frequency: "1" },
    { word: "want", frequency: "2" },
    { word: "was", frequency: "1" },
    { word: "watch", frequency: "1" },
    { word: "water", frequency: "1" },
    { word: "wax", frequency: "1" },
    { word: "we", frequency: "2" },
    { word: "were", frequency: "1" },
    { word: "what", frequency: "1" },
    { word: "when", frequency: "1" },
    { word: "whisper", frequency: "1" },
    { word: "who", frequency: "1" },
    { word: "why", frequency: "1" },
    { word: "will", frequency: "1" },
    { word: "wind", frequency: "1" },
    { word: "with", frequency: "2" },
    { word: "woman", frequency: "1" },
    { word: "worship", frequency: "1" },
    { word: "y", frequency: "4" },
    { word: "yet", frequency: "1" },
    { word: "you", frequency: "4" },
  ];
  const wordState = words.map((word) => {
    const [top, left] = scatter();
    return {
      value: word.word,
      id: nanoid(),
      top: top,
      left: left,
    };
  });
  // const wordState = [
  //   { value: "fridge", top: 80, left: 20 },
  //   { value: "magnet", top: 100, left: 85 },
  //   { value: "poetry", top: 120, left: 160 },
  // ];

  const spanElements = wordState.map((word, i) => (
    <Word key={i} top={word.top} left={word.left}>
      {word.value}
    </Word>
  ));

  const style = {
    height: "100vh",
    width: "100vw",
    position: "absolute",
  };

  return <div style={style}>{spanElements}</div>;
}

export default App;
